### ISSUE TITLE
500 error while log-in

### ISSUE THREAD

**Issue by clawfire** [Xav-74/myBMW#2]
Hi there,
When trying to configure a car, I got a 500 error. 
Nothing in the log of Jeedom but I can see this returned with the 500 error in the AJAX call 
```json
{
    "state": "error",
    "result": "<span id=\"span_errorMessage\">Aucune méthode correspondante à : </span>",
    "code": 0
}
```
Also, my email has a + in it, sometimes, some escaping are not made well and that create an issue 😁

**Comment by clawfire** [comment]
Ok so you have to save the details first **before** syncing 😁

**Comment by Xav-74** [comment]
> Ok so you have to save the details first **before** syncing 😁

Correct 😜

**Comment by Xav-74** [comment]
For your information, I put a fix for this issue ;)
The eqLogic is now automatically saved before synchronization

**Comment by clawfire** [comment]
Awesome 👍🏼
