### ISSUE TITLE
403 forbidden when trying to sync

### ISSUE THREAD

**Issue by clawfire** [Xav-74/myBMW#3]
I'm trying to sync my mini and I double check my credentials but when trying to sync I got a 

```
└─End of synchronisation : [403 - FORBIDDEN]
```

**Comment by Xav-74** [comment]
Hi @clawfire 

Could you update the plugin (stable or beta) ?
The last version (from 2022/07/25 22:23) uses the new vehicle API v2 and solves this issue 😜

Xav

**Comment by clawfire** [comment]
Works well now 😃 
Thanks 👍🏼

**Comment by Xav-74** [comment]
You’re welcome 😜
