### ISSUE TITLE
Multiple dates identiques sur les graphiques du panel

### ISSUE THREAD

**Issue by jpty** [Xav-74/myBMW#8]
Exemple sur le graphique Niveau carburant:
![image](https://github.com/user-attachments/assets/784d9f6c-a668-4196-9777-269484f0f487)

Le PR https://github.com/Xav-74/myBMW/pull/9 permet d'afficher l'heure :
![image](https://github.com/user-attachments/assets/2aa93e50-e1ea-44d8-99ca-9a1caa500477)

**Comment by Xav-74** [comment]
Merci pour le PR - Merge OK
